### ISSUE TITLE
Umstellung auf Version 2

### ISSUE THREAD

**Issue by HDValentin** [haschek/PubwichFork#28]
Ich habe meine Pubwich 1.x Installation
http://www.vbachem.de/pubwich/
testweise auf die Version 2.0 aktualisiert:
http://www.vbachem.de/pubwich2/

Übernommen habe ich von Hand die Einstellung in der Config-Datei.
Alle anderen Änderungen habe ich einmal bewusst heraus gelassen, dass wir sehen wo Anpassungen nötig sind, die du vielleicht in das nächste Release einbauen kannst:
- Twitter: Formatierung und Verlinkung stimmt nicht
- Twitter eigener Benutzername sollte nicht auftauchen
- 500px Bilder einbinden
- Die Größe der Flickr-Bilder kann ich wahrscheinlich im Theme ändern, oder?
- Eigener Blog: Hier wäre das zum Beitrag gehörende Foto schön, wenn es mit angezeigt würde.

Lässt sich 500px auch so einbinden wir der Flickr-Block?
Funktioniert die Einbindung von Picasa-Fotos?

Viele Grüße
Valentin

**Comment by haschek** [comment]
Für fast alle Punkte gilt: du musst natürlich auch deine Filter aus dem Theme noch mit übernehmen. Layout läuft komplett über CSS, dort kannst du auch die Bildergrößen ändern. Und Bilder werden zu den EInträgen angezeigt, wenn der Feed entsprechende Mediainfos beinhaltet.
