### ISSUE TITLE
Implement Steam service

### ISSUE THREAD

**Issue by Warrows** [haschek/PubwichFork#36]

**Comment by shinmai** [comment]
What data would be displayed, exactly? The only thing in the API that looks like it would fit a pubwich page is GetRecentlyPlayedGames, which returns the app id's of the apps the user has run in the previous 14 days, along with playtime (overall and last 2 weeks), and if there is a public store page for the app also a human readable name and links to a 32x32 icon and a 184x69 logo.

**Comment by Warrows** [comment]
The list of the games recently played would perfectly fit I guess.

**Comment by haschek** [comment]
Please provide links to API docs if you request a new service class.

**Comment by Warrows** [comment]
Hey @haschek , I am going to work on this. Can you assign the task to me ?
BTW, here is the current API I am going to work on for the Steam service : https://partner.steamgames.com/doc/webapi_overview

**Comment by haschek** [comment]
@Warrows Sorry for the delay, I was in vacation when you wrote your comment, thx for the support!
