### ISSUE TITLE
YouTube is not working

### ISSUE THREAD

**Issue by HDValentin** [haschek/PubwichFork#37]
On my Pubwich the youtube-service stops working:
http://www.vbachem.de/pubwich/

Any ideas for reparing that?

**Comment by haschek** [comment]
Probably HTTPS, PubwichFork development branch should work, I really need to build a intermediate version that can be released soon.

**Comment by haschek** [comment]
Not just HTTPS, Google switched off v2-RSS-API, need to change the Service class to v3 that is completely different from v2.

**Comment by haschek** [comment]
Youtube aggregation is fixed in development branch. See the wiki.
- https://github.com/haschek/PubwichFork/tree/development
- https://github.com/haschek/PubwichFork/wiki/ServiceYoutube
