### ISSUE TITLE
facebook: Cannot query users by their username 

### ISSUE THREAD

**Issue by Pixafin** [haschek/PubwichFork#38]
i do have the latest version installed.
twitter works perfect, but facebook shows:
`An error occured with the FacebookPage API. The data is therefore unavailable.`

apache2 error log shows:
`PHP Warning:  file_get_contents(https://graph.facebook.com/v2.4/MYNAME/posts?fields=id,status_type,type,story,message,created_time,picture,full_picture,name,caption,link&amp;limit=5&amp;access_token=MYTOKEN): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found\r\n in /var/www/html/pubwichfork/app/core/FileFetcher.php on line 39`

if i open the url in a browser i do get:
`{
error: {
message: "(#803) Cannot query users by their username (MYNAME)",
type: "OAuthException",
code: 803,
fbtrace_id: "someID"
}
}`

if i google for #803 it looks like the request with username is depricated since 2014. but this soft got updated in 2015. what's wrong?

**Comment by Pixafin** [comment]
idiot me. 

as declared in https://github.com/haschek/PubwichFork/wiki/ServiceFacebook
`This service integrates public posts from Facebook pages within your PubwichFork page.`
it only works with pages.

so, configuring a page and not a user works

**Comment by haschek** [comment]
Thank you for the feedback. Yes, PubwichFork currently only aggregates data from Facebook pages, not user profiles.
