### ISSUE TITLE
Installed the dev and ran into error messages

### ISSUE THREAD

**Issue by HDValentin** [haschek/PubwichFork#44]
I've just installed a fresh copy of the development version of pubwich fork to
https://vbachem.de/pubwich2/
My Php-Version is 7.1.7

Now I get the following Warnigs and Erros:
Warning: require_once(Cache/Lite.php): failed to open stream: No such file or directory in /var/www/virtual/bachem/html/pubwich2/app/core/Pubwich.php on line 107

Fatal error: require_once(): Failed opening required 'Cache/Lite.php' (include_path='/var/www/virtual/bachem/html/pubwich2/usr:/var/www/virtual/bachem/html/pubwich2/app::::.:/package/host/localhost/php-7.1.7/lib/php') in /var/www/virtual/bachem/html/pubwich2/app/core/Pubwich.php on line 107

I know it is a dev-version. But do you have any idea how to solve this?

**Comment by HDValentin** [comment]
So, I installed Cache_Lite successful, I guess:

Now I get the following message, And I don't know how to install the mustache:
Warning: require_once(mustache.php/src/Mustache/Autoloader.php): failed to open stream: No such file or directory in /var/www/virtual/bachem/html/pubwich2/app/core/Pubwich.php on line 114

Fatal error: require_once(): Failed opening required 'mustache.php/src/Mustache/Autoloader.php' (include_path='/var/www/virtual/bachem/html/pubwich2/usr:/var/www/virtual/bachem/html/pubwich2/app::::.:/home/bachem/pear/php:/package/host/localhost/php-7.0/lib/php') in /var/www/virtual/bachem/html/pubwich2/app/core/Pubwich.php on line 114

**Comment by Warrows** [comment]
Yeah, I guess the install instructions could use a refresher. Feel free to add what you think is missing in the wiki once your issue is resolved.
As for your problem, did you run `bower install` ? What was the output, everything ok with it ?
Maybe try running it again
`rm -rf bower_components`
`bower cache clean`
`bower install`
And give us the output.

**Comment by HDValentin** [comment]
I don't think that I have a bower in a normal hosting.
Is it a requirenment for using pubwich fork?

**Comment by Warrows** [comment]
Well it's a package manager and it does the job of installing all you need for you. Alternatively you can do it by yourself. But in this case you have to find out each dependency and all the dependencies' dependencies . And how to install them.
Concerning mustache I guess you can start from there : https://github.com/bobthecow/mustache.php

**Comment by HDValentin** [comment]
So I've just tried a fresh installtion.

On my uberspace I could install bower with "npm install -g --prefix=$HOME bower"

I run
"$ git clone https://github.com/haschek/PubwichFork.git
$ cd PubwichFork
$ git pull
$ bower install"

This was the output:
"/home/bachem$ rm -rf bower_components
/home/bachem$ bower cache clean
/home/bachem$ bower install
bower                           ENOENT No bower.json present
/home/bachem$ git clone https://github.com/haschek/PubwichFork.git
Cloning into 'PubwichFork'...
/home/bachem$ cd PubwichFork
/home/bachem/PubwichFork$ git pull
Already up-to-date.
/home/bachem/PubwichFork$ bower install
[{
  "level": "warn",
  "id": "invalid-meta",
  "message": "for:/home/bachem/PubwichFork/bower.json",
  "data": {}
}, {
  "level": "warn",
  "id": "invalid-meta",
  "message": "The \"name\" is recommended to be lowercase, can contain digits, dots, dashes",
  "data": {}
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz#*",
  "data": {
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "resolver": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz#*",
  "data": {
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "resolver": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php#*",
  "data": {
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "resolver": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php#*",
  "data": {
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "resolver": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://github.com/simplepie/simplepie.git#1.3.1",
  "data": {
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "resolver": {
      "name": "simplepie",
      "source": "https://github.com/simplepie/simplepie.git",
      "target": "1.3.1"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://github.com/simplepie/simplepie.git#1.3.1",
  "data": {
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "resolver": {
      "name": "simplepie",
      "source": "https://github.com/simplepie/simplepie.git",
      "target": "1.3.1"
    }
  }
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://github.com/pear/pear-core-minimal.git#*",
  "data": {
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "resolver": {
      "name": "pear-core",
      "source": "https://github.com/pear/pear-core-minimal.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://github.com/pear/pear-core-minimal.git#*",
  "data": {
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "resolver": {
      "name": "pear-core",
      "source": "https://github.com/pear/pear-core-minimal.git",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://github.com/pear/Cache_Lite.git#*",
  "data": {
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "resolver": {
      "name": "pear-cache-lite",
      "source": "https://github.com/pear/Cache_Lite.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://github.com/pear/Cache_Lite.git#*",
  "data": {
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "resolver": {
      "name": "pear-cache-lite",
      "source": "https://github.com/pear/Cache_Lite.git",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "not-cached",
  "message": "https://github.com/bobthecow/mustache.php.git#v2.5.1",
  "data": {
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "resolver": {
      "name": "mustache.php",
      "source": "https://github.com/bobthecow/mustache.php.git",
      "target": "v2.5.1"
    }
  }
}, {
  "level": "action",
  "id": "resolve",
  "message": "https://github.com/bobthecow/mustache.php.git#v2.5.1",
  "data": {
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "resolver": {
      "name": "mustache.php",
      "source": "https://github.com/bobthecow/mustache.php.git",
      "target": "v2.5.1"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
  "data": {
    "url": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
    "to": "/tmp/bachem/bower/f757752d15314b1544c0d5e8101f7828-24566-vMoRiS/php-gettext-1.0.11.tar.gz",
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "resolver": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
  "data": {
    "url": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
    "to": "/tmp/bachem/bower/045bfa58b0daf12198188a1d6fdad9d5-24566-gGb4jz/OAuth.php",
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "resolver": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php#e-tag:9dc9a99b7",
  "data": {
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "resolver": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "extract",
  "message": "php-gettext-1.0.11.tar.gz",
  "data": {
    "archive": "/tmp/bachem/bower/f757752d15314b1544c0d5e8101f7828-24566-vMoRiS/php-gettext-1.0.11.tar.gz",
    "to": "/tmp/bachem/bower/f757752d15314b1544c0d5e8101f7828-24566-vMoRiS",
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "resolver": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
  "data": {
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "resolver": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://github.com/pear/pear-core-minimal/archive/v1.10.3.tar.gz",
  "data": {
    "url": "https://github.com/pear/pear-core-minimal.git",
    "to": "/tmp/bachem/bower/5bc23cce5b4f127532c873400d4c7616-24566-UMmbT1/archive.tar.gz",
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "resolver": {
      "name": "pear-core",
      "source": "https://github.com/pear/pear-core-minimal.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://github.com/simplepie/simplepie/archive/1.3.1.tar.gz",
  "data": {
    "url": "https://github.com/simplepie/simplepie.git",
    "to": "/tmp/bachem/bower/b95abded121a85e9fdc9029db2a83eaf-24566-fCTrfS/archive.tar.gz",
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "resolver": {
      "name": "simplepie",
      "source": "https://github.com/simplepie/simplepie.git",
      "target": "1.3.1"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://github.com/pear/Cache_Lite/archive/v1.8.0.tar.gz",
  "data": {
    "url": "https://github.com/pear/Cache_Lite.git",
    "to": "/tmp/bachem/bower/0bf57c221ca59510f575c1032be1a249-24566-lj7yEL/archive.tar.gz",
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "resolver": {
      "name": "pear-cache-lite",
      "source": "https://github.com/pear/Cache_Lite.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "download",
  "message": "https://github.com/bobthecow/mustache.php/archive/v2.5.1.tar.gz",
  "data": {
    "url": "https://github.com/bobthecow/mustache.php.git",
    "to": "/tmp/bachem/bower/37ae446288a49d03beb81cb8c5e3f931-24566-OJOVmu/archive.tar.gz",
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "resolver": {
      "name": "mustache.php",
      "source": "https://github.com/bobthecow/mustache.php.git",
      "target": "v2.5.1"
    }
  }
}, {
  "level": "action",
  "id": "extract",
  "message": "archive.tar.gz",
  "data": {
    "archive": "/tmp/bachem/bower/5bc23cce5b4f127532c873400d4c7616-24566-UMmbT1/archive.tar.gz",
    "to": "/tmp/bachem/bower/5bc23cce5b4f127532c873400d4c7616-24566-UMmbT1",
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "resolver": {
      "name": "pear-core",
      "source": "https://github.com/pear/pear-core-minimal.git",
      "target": "*"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://github.com/pear/pear-core-minimal.git#1.10.3",
  "data": {
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "resolver": {
      "name": "pear-core",
      "source": "https://github.com/pear/pear-core-minimal.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "extract",
  "message": "archive.tar.gz",
  "data": {
    "archive": "/tmp/bachem/bower/0bf57c221ca59510f575c1032be1a249-24566-lj7yEL/archive.tar.gz",
    "to": "/tmp/bachem/bower/0bf57c221ca59510f575c1032be1a249-24566-lj7yEL",
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "resolver": {
      "name": "pear-cache-lite",
      "source": "https://github.com/pear/Cache_Lite.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "extract",
  "message": "archive.tar.gz",
  "data": {
    "archive": "/tmp/bachem/bower/37ae446288a49d03beb81cb8c5e3f931-24566-OJOVmu/archive.tar.gz",
    "to": "/tmp/bachem/bower/37ae446288a49d03beb81cb8c5e3f931-24566-OJOVmu",
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "resolver": {
      "name": "mustache.php",
      "source": "https://github.com/bobthecow/mustache.php.git",
      "target": "v2.5.1"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://github.com/pear/Cache_Lite.git#1.8.0",
  "data": {
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "resolver": {
      "name": "pear-cache-lite",
      "source": "https://github.com/pear/Cache_Lite.git",
      "target": "*"
    }
  }
}, {
  "level": "action",
  "id": "extract",
  "message": "archive.tar.gz",
  "data": {
    "archive": "/tmp/bachem/bower/b95abded121a85e9fdc9029db2a83eaf-24566-fCTrfS/archive.tar.gz",
    "to": "/tmp/bachem/bower/b95abded121a85e9fdc9029db2a83eaf-24566-fCTrfS",
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "resolver": {
      "name": "simplepie",
      "source": "https://github.com/simplepie/simplepie.git",
      "target": "1.3.1"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://github.com/bobthecow/mustache.php.git#2.5.1",
  "data": {
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "resolver": {
      "name": "mustache.php",
      "source": "https://github.com/bobthecow/mustache.php.git",
      "target": "v2.5.1"
    }
  }
}, {
  "level": "info",
  "id": "resolved",
  "message": "https://github.com/simplepie/simplepie.git#1.3.1",
  "data": {
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "resolver": {
      "name": "simplepie",
      "source": "https://github.com/simplepie/simplepie.git",
      "target": "1.3.1"
    }
  }
}, {
  "level": "action",
  "id": "install",
  "message": "php-oauth#e-tag:9dc9a99b7",
  "data": {
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/d72e7a1a83aad6baef74991b8f164ccc/_wildcard",
    "pkgMeta": {
      "name": "php-oauth",
      "_cacheHeaders": {
        "ETag": "\"9dc9a99b750ba6439c8dd8f704b5a9d0b9b8f0c1\"",
        "Content-Length": "7319",
        "Content-Type": "text/plain; charset=utf-8"
      },
      "_release": "e-tag:9dc9a99b7",
      "main": "index.php",
      "_source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}, {
  "level": "action",
  "id": "install",
  "message": "php-gettext",
  "data": {
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/d4d4355216e8f77af8a3a2ad02321427/_wildcard",
    "pkgMeta": {
      "name": "php-gettext",
      "_cacheHeaders": {
        "Last-Modified": "Fri, 24 Dec 2010 23:45:51 GMT",
        "Content-Length": "20913",
        "Content-Type": "application/x-tar"
      },
      "_source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}, {
  "level": "action",
  "id": "install",
  "message": "pear-core#1.10.3",
  "data": {
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/f326995e398cacf7663e4d9709cb3d1a/1.10.3",
    "pkgMeta": {
      "name": "pear-core",
      "homepage": "https://github.com/pear/pear-core-minimal",
      "version": "1.10.3",
      "_release": "1.10.3",
      "_resolution": {
        "type": "version",
        "tag": "v1.10.3",
        "commit": "070f0b600b2caca2501e2c9b7e553016e4b0d115"
      },
      "_source": "https://github.com/pear/pear-core-minimal.git",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}, {
  "level": "action",
  "id": "install",
  "message": "pear-cache-lite#1.8.0",
  "data": {
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/e5d992aec39c242d06904cc1cdbcdd76/1.8.0",
    "pkgMeta": {
      "name": "pear-cache-lite",
      "homepage": "https://github.com/pear/Cache_Lite",
      "version": "1.8.0",
      "_release": "1.8.0",
      "_resolution": {
        "type": "version",
        "tag": "v1.8.0",
        "commit": "467bcc0bc86d58883ba1e35c01a2fd40e75f2d96"
      },
      "_source": "https://github.com/pear/Cache_Lite.git",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}, {
  "level": "action",
  "id": "install",
  "message": "mustache.php#2.5.1",
  "data": {
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/8858b911d57160cfcadea6b094a44280/2.5.1",
    "pkgMeta": {
      "name": "mustache.php",
      "homepage": "https://github.com/bobthecow/mustache.php",
      "version": "2.5.1",
      "_release": "2.5.1",
      "_resolution": {
        "type": "version",
        "tag": "v2.5.1",
        "commit": "2a250235ef52c9433d8e73649a2b093be68df8de"
      },
      "_source": "https://github.com/bobthecow/mustache.php.git",
      "_target": "v2.5.1"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}, {
  "level": "action",
  "id": "install",
  "message": "simplepie#1.3.1",
  "data": {
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "canonicalDir": "/home/bachem/.cache/bower/packages/d2dea9ce47ba2584aa61c2ac1322722a/1.3.1",
    "pkgMeta": {
      "name": "simplepie",
      "homepage": "https://github.com/simplepie/simplepie",
      "version": "1.3.1",
      "_release": "1.3.1",
      "_resolution": {
        "type": "version",
        "tag": "1.3.1",
        "commit": "e9472a1547882057efaca81ae1ec6d93d802e57d"
      },
      "_source": "https://github.com/simplepie/simplepie.git",
      "_target": "1.3.1"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}]
{
  "php-oauth": {
    "endpoint": {
      "name": "php-oauth",
      "source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/php-oauth",
    "pkgMeta": {
      "name": "php-oauth",
      "_cacheHeaders": {
        "ETag": "\"9dc9a99b750ba6439c8dd8f704b5a9d0b9b8f0c1\"",
        "Content-Length": "7319",
        "Content-Type": "text/plain; charset=utf-8"
      },
      "_release": "e-tag:9dc9a99b7",
      "main": "index.php",
      "_source": "https://raw.githubusercontent.com/jtsternberg/oauth/master/code/php/OAuth.php",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  },
  "php-gettext": {
    "endpoint": {
      "name": "php-gettext",
      "source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/php-gettext",
    "pkgMeta": {
      "name": "php-gettext",
      "_cacheHeaders": {
        "Last-Modified": "Fri, 24 Dec 2010 23:45:51 GMT",
        "Content-Length": "20913",
        "Content-Type": "application/x-tar"
      },
      "_source": "https://launchpad.net/php-gettext/trunk/1.0.11/+download/php-gettext-1.0.11.tar.gz",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  },
  "pear-core": {
    "endpoint": {
      "name": "pear-core",
      "source": "pear/pear-core-minimal",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/pear-core",
    "pkgMeta": {
      "name": "pear-core",
      "homepage": "https://github.com/pear/pear-core-minimal",
      "version": "1.10.3",
      "_release": "1.10.3",
      "_resolution": {
        "type": "version",
        "tag": "v1.10.3",
        "commit": "070f0b600b2caca2501e2c9b7e553016e4b0d115"
      },
      "_source": "https://github.com/pear/pear-core-minimal.git",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  },
  "pear-cache-lite": {
    "endpoint": {
      "name": "pear-cache-lite",
      "source": "pear/Cache_Lite",
      "target": "*"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/pear-cache-lite",
    "pkgMeta": {
      "name": "pear-cache-lite",
      "homepage": "https://github.com/pear/Cache_Lite",
      "version": "1.8.0",
      "_release": "1.8.0",
      "_resolution": {
        "type": "version",
        "tag": "v1.8.0",
        "commit": "467bcc0bc86d58883ba1e35c01a2fd40e75f2d96"
      },
      "_source": "https://github.com/pear/Cache_Lite.git",
      "_target": "*"
    },
    "dependencies": {},
    "nrDependants": 1
  },
  "mustache.php": {
    "endpoint": {
      "name": "mustache.php",
      "source": "bobthecow/mustache.php",
      "target": "v2.5.1"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/mustache.php",
    "pkgMeta": {
      "name": "mustache.php",
      "homepage": "https://github.com/bobthecow/mustache.php",
      "version": "2.5.1",
      "_release": "2.5.1",
      "_resolution": {
        "type": "version",
        "tag": "v2.5.1",
        "commit": "2a250235ef52c9433d8e73649a2b093be68df8de"
      },
      "_source": "https://github.com/bobthecow/mustache.php.git",
      "_target": "v2.5.1"
    },
    "dependencies": {},
    "nrDependants": 1
  },
  "simplepie": {
    "endpoint": {
      "name": "simplepie",
      "source": "simplepie/simplepie",
      "target": "1.3.1"
    },
    "canonicalDir": "/home/bachem/PubwichFork/app/vendor/simplepie",
    "pkgMeta": {
      "name": "simplepie",
      "homepage": "https://github.com/simplepie/simplepie",
      "version": "1.3.1",
      "_release": "1.3.1",
      "_resolution": {
        "type": "version",
        "tag": "1.3.1",
        "commit": "e9472a1547882057efaca81ae1ec6d93d802e57d"
      },
      "_source": "https://github.com/simplepie/simplepie.git",
      "_target": "1.3.1"
    },
    "dependencies": {},
    "nrDependants": 1
  }
}"

On the first run, I've got the following Messages:
"
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; idna_convert has a deprecated constructor in /var/www/virtual/bachem/html/PubwichFork/app/vendor/simplepie/idn/idna_convert.class.php on line 54
Notice: Undefined index: username in /var/www/virtual/bachem/html/PubwichFork/app/services/Twitter.php on line 79
Notice: Undefined index: username in /var/www/virtual/bachem/html/PubwichFork/app/services/Twitter.php on line 80
Notice: Undefined index: username in /var/www/virtual/bachem/html/PubwichFork/app/services/Twitter.php on line 81
Notice: Undefined index: username in /var/www/virtual/bachem/html/PubwichFork/app/services/Twitter.php on line 83"

**Comment by HDValentin** [comment]
https://vbachem.de/PubwichFork/

**Comment by Warrows** [comment]
This looks good. Your bower installed a lot of dependencies and you are only getting a few warnings because your twitter configuration is wrong and one method is deprecated. Which is fair given the level of maintenance the app is getting.

**Comment by HDValentin** [comment]
But a beginner with a normal click and go hosting can't install this.
In earlier Versions this was possible.

What can I do to get rid of the twitter error messages?

**Comment by Warrows** [comment]
Not sure about the earlier versions since I was not around. But given what you need to do (get api keys and whatnot) to configure most services, I think it's not for click and go hosting anyway. Maybe we would need some input from @haschek on this.
Concerning your twitter I guess you just forgot to fill the "username" field or something like that.

**Comment by HDValentin** [comment]
Thanks, it was the variable of the twitter name. In former versions of the configuration it was named different.

Now I changed the language and the date-format to de_DE and de_DE.UTF8 and got at the first access of the page the following messages:

"Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor in /var/www/virtual/bachem/html/PubwichFork/app/vendor/php-gettext/streams.php on line 48

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor in /var/www/virtual/bachem/html/PubwichFork/app/vendor/php-gettext/streams.php on line 84

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; CachedFileReader has a deprecated constructor in /var/www/virtual/bachem/html/PubwichFork/app/vendor/php-gettext/streams.php on line 145

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor in /var/www/virtual/bachem/html/PubwichFork/app/vendor/php-gettext/gettext.php on line 36"

**Comment by Warrows** [comment]
That's a deprecation in a dependency. No big deal. I'll look into it but it should not cause you any problem apart from this warnings.

**Comment by HDValentin** [comment]
The bower install worked for me on my uberspace.de hosting.
It was hard for me to install it. A stepp by stepp guide and a list of the requirenments would be great.
I know that this is the development branch.

**Comment by haschek** [comment]
@Warrows Thank you for helping out Valentin, very appreciated!

@HDValentin As long as it is a development version there won't be be an archive that contains all dependencies. The only way is to check it out via git and use all the developing tools (e.g. bower) to prepare the deployment. I always would suggest to do work on a local machine and deploy it on stating/production server when everything is ready.

I will address the issues with insta and the docs directly there in the open issues.

About maintainment: I only have a few time to maintain the project, I mostly do it when I have to do some work for an agency who use it for clients, or if I need extensions and fixes for my own sites powered by PubwichFork. The user base is too small to put more effort into the software. But currently I do not plan to put it down, so there will be updates (at least in evelopment) and I'm happy about every user who contributes via coding, issue tracking or finding improvements for the documentation.
