### ISSUE TITLE
twitter.php profile_image_url is not https://

### ISSUE THREAD

**Issue by HDValentin** [haschek/PubwichFork#47]
The embedded Images (Twitter-Profile-Pics) are embedded via https:// and I don't know where to change that. When I call the profile image direc in my brpwser it showes me a https:// path. In Pubwich it is http://

e.g:  on https://www.vbachem.de/PubwichFork/
direct https://pbs.twimg.com/profile_images/2396986794/5m988daigb0o9nqupd90_normal.png
embedded http://pbs.twimg.com/profile_images/2396986794/5m988daigb0o9nqupd90_normal.png

![screenshot 2017-08-05 01 17 36](https://user-images.githubusercontent.com/1276955/28990320-a1c9b578-797c-11e7-8b48-f62dc009871f.jpg)

**Comment by HDValentin** [comment]
Twitter introduced a new variable for images with https: "profile_image_url_https" instead of "profile_image_url"
Source: https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object
Probably there are more changes that a worth to take a look on.
Changing the variable in /app/services/Twitter.php solves the problem with the Lock in the url bar.
'user_image' => $item->user->profile_image_url,

**Comment by haschek** [comment]
@HDValentin This is fixed in release/v2.9 branch (and lot of more stuff), could you test that branch with your configuration and template?

**Comment by HDValentin** [comment]
@haschek I've replaced the service-folder and deleted the cache. This ist the result:
https://www.vbachem.de/PubwichFork/
I can see unsharp twitter-user-images on other browsers, On Firefox they are not shown.
Instagram is not working. I think they have changed their api.

**Comment by HDValentin** [comment]
In Microsoft Edge the Site is very tiny and not usable.

**Comment by HDValentin** [comment]
![zwischenablage01](https://user-images.githubusercontent.com/1276955/39726901-e123aaf0-5250-11e8-848e-18bceb0bce02.jpg)
![zwischenablage02](https://user-images.githubusercontent.com/1276955/39726905-e67449a6-5250-11e8-9ea8-47a1d1d1bac2.jpg)
![zwischenablage03](https://user-images.githubusercontent.com/1276955/39726906-eb01bb20-5250-11e8-9263-badd87aa4f27.jpg)
![zwischenablage04](https://user-images.githubusercontent.com/1276955/39726913-ef2da4b6-5250-11e8-8bfb-6d94e1d0ce34.jpg)

Screenshots from my issuses. First ist Microsoft Edge, the others are Mozilla Firefox.
