### ISSUE TITLE
Flickr service, image sizes

### ISSUE THREAD

**Issue by HDValentin** [haschek/PubwichFork#50]
In the config.php is a comment at the flickr service that you can use different sizes:
'size' => 's', // s|q|t|m|n|z|c
If I change the size value in my config.php, the script is loading bigger images, but the imagessize in Pubwich ist not getting bigger.
Probably there is some CSS missing for that function to work.

At the moment I have the value 'q' wich serves images with 150x150 pixel. They are scaled to 102x102 Pixel:
 https://www.vbachem.de/PubwichFork/

**Comment by haschek** [comment]
This behaviour is correct. The PubwichFork default theme only needs small thumbnails. If a user decide to use an own theme or just an own mustache template for Flickr and an extended CSS, bigger image sizes may be necessary. The service configuration is very important for the data aggregation, not so strong releated to the theme and display of the data later.

**Comment by HDValentin** [comment]
OK, thank you for the Info. I thought it should work already when changing the size in the config. :-)
